platform :ios, '9.0'

target 'Todoey' do

  use_modular_headers!

  # Pods for Todoey

pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
